### ISSUE TITLE
Remove secrets from .env, confirm that secrets are rotated in your app (they must all be changed)

### ISSUE THREAD

**Issue by jon-bell** [classee-cloud/service-github#4]

**Comment by rajatkeshri** [comment]
Updated in the existing PR

**Comment by jon-bell** [comment]
Could you please link to the commit that addresses this? One way to make this easier in the future is to put something like "work on issue #4" in the commit message, and then GitHub will auto-cross-ref.

**Comment by rajatkeshri** [comment]
Makes sense. Okay ill keep this in mind for the next PRs

CommitID - 0b0636db38931696cc262cf5ef67a7778f26e092
PR - https://github.com/classee-cloud/service-github/pull/3
